### ISSUE TITLE
No ring information Kitti data does not have laser ring information

### ISSUE THREAD

**Issue by Halilg33** [hafeezhusain/stereo_depth_correction#1]
Hi,

I want to use your code to upsample velodyne data from Kitti dataset. But this data just have XYZI information rather than XYZIR. I notice that ring information is needed to process the data.

You mentioned in your paper that you have evaluated this algorithm successfully on the Kitti dataset. My question is how can I obtain ring information? 

Thanks

**Comment by hafeezhusain** [comment]
Hi!

KITTI data are sorted. The points are recorded in an orderly manner, the points of one ring follow the points of another in the direction of laser rotation. Rings can be separated by tracing the change of the quadrant.

I used the following pieces of code for this purpose:

int get_quadrant(pcl::PointXYZ point)
{
	int res = 0;
	float x = point.x;
	float y = point.y;
	if (x > 0 && y >= 0)
		res = 1;
	else if (x <= 0 && y > 0)
		res = 2;
	else if (x < 0 && y <= 0)
		res = 3;
	else if (x >= 0 && y < 0)
		res = 4;
	return res;
}

void add_ring_info(pcl::PointCloud<pcl::PointXYZ>& input, pcl::PointCloud<Velodyne::Point>& output)
{
	int previous_quadrant = 0;
	uint16_t ring_ = (uint16_t)RINGS_COUNT-1;
	for (pcl::PointCloud<pcl::PointXYZ>::iterator pt = input.points.begin(); pt < input.points.end()-1; ++pt){
		int quadrant = get_quadrant(*pt);
		if (quadrant == 1 && previous_quadrant == 4 && ring_ > 0)
			ring_ -= 1;
		Velodyne::Point point;
		point.x = pt->x;
		point.y = pt->y;
		point.z = pt->z;
		point.ring = ring_;
		output.push_back(point);
		previous_quadrant = quadrant;
	}
}

**Comment by Halilg33** [comment]
Hi,

thank you. Code is working now and I get the desired fused output :) but unfortunately not very long. After 2-3s I get a error msg "Segmentation fault (core dumped)". Do you have an idea what goes wrong here?

I am working on a rosbag file from kitti data. Stereo+LiDAR output works. My GPU is a 1080gtx and CPU is a AMD ryzen7 2750x. Dunno why the core gets dumped all the time...

Appreciate your help.

**Comment by Halilg33** [comment]
Hi,

thank you. Code is working now and I get the desired fused output :) but unfortunately not very long. After 2-3s I get a error msg "Segmentation fault (core dumped)". Do you have an idea what goes wrong here?

I am working on a rosbag file from kitti data. Stereo+LiDAR output works. My GPU is a 1080gtx and CPU is a AMD ryzen7 2750x. Dunno why the core gets dumped all the time...

Appreciate your help.
